coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
        informational: true
    patch:
      default:
        target: auto
        threshold: 50%
        informational: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
